version: "3"
services:
  fastrl: &fastrl
    restart: unless-stopped
    working_dir: /home/fastrl_user/fastrl
    build:
      dockerfile: fastrl.Dockerfile
      context: .
#    image: josiahls/fastrl:latest
    image: fastrl:latest
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    logging:
      driver: json-file
      options:
        max-size: 50m
    stdin_open: true
    tty: true
    volumes:
      - .:/home/fastrl_user/fastrl/

  notebook:
    <<: *fastrl
    command: /bin/bash -c ../run_jupyter.sh
    ports:
      - "8080:8080"

  watcher:
    <<: *fastrl
    command: watchmedo shell-command --command nbdev_build_docs --pattern *.ipynb --recursive --drop
    network_mode: host # for GitHub Codespaces https://github.com/features/codespaces/

  jekyll:
    restart: unless-stopped
    working_dir: /home/fastrl_user/fastrl/
    image: fastdotai/nbdev-docs:latest
    logging:
      driver: json-file
      options:
        max-size: 50m
    stdin_open: true
    tty: true
    volumes:
      - .:/home/fastrl_user/fastrl/
    ports:
     - "4000:4000"
    command: >
     bash -c "cd docs
     && bundle i
     && chmod -R u+rwx . && bundle exec jekyll serve --host 0.0.0.0"