# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PixelObservationWrapper": "01_wrappers.ipynb",
         "STATE_KEY": "01_wrappers.ipynb",
         "ActionSelector": "03_basic_agents.ipynb",
         "ArgmaxActionSelector": "03_basic_agents.ipynb",
         "EpsilonGreedyActionSelector": "03_basic_agents.ipynb",
         "ProbabilityActionSelector": "03_basic_agents.ipynb",
         "default_states_preprocessor": "03_basic_agents.ipynb",
         "float32_preprocessor": "03_basic_agents.ipynb",
         "BaseAgent": "03_basic_agents.ipynb",
         "TestAgent": "03_basic_agents.ipynb",
         "DiscreteAgent": "03_basic_agents.ipynb",
         "DQNAgent": "03_basic_agents.ipynb",
         "TargetNet": "03_basic_agents.ipynb",
         "PolicyAgent": "03_basic_agents.ipynb",
         "ActorCriticAgent": "03_basic_agents.ipynb",
         "AgentLearner": "06_basic_train.ipynb",
         "TfmdSourceDL": "05a_data.ipynb",
         "SourceExhausted": "05a_data.ipynb",
         "TfmdSource": "05a_data.ipynb",
         "IterableDataBlock": "05a_data.ipynb",
         "MakeTfm": "05a_data.ipynb",
         "env_display": "05a_data.ipynb",
         "Experience": "05a_data.ipynb",
         "envlen": "05a_data.ipynb",
         "ResetAndStepTfm": "05a_data.ipynb",
         "ExperienceBlock": "05a_data.ipynb",
         "FirstLastTfm": "05a_data.ipynb",
         "FirstLastExperienceBlock": "05a_data.ipynb",
         "template_data_fit": "05b_async_data.ipynb",
         "DataFitProcess": "05b_async_data.ipynb",
         "MultiProcessTfm": "05b_async_data.ipynb",
         "AsyncExperienceBlock": "05b_async_data.ipynb",
         "FloatifyCallback": "06_basic_train.ipynb",
         "FakeRunCallback": "06_basic_train.ipynb",
         "LatentLossBuffer": "06_basic_train.ipynb",
         "LinearA2C": "12_a3c.a3c_data.ipynb",
         "r_estimate": "12_a3c.a3c_data.ipynb",
         "unbatch": "12_a3c.a3c_data.ipynb",
         "loss_func": "12_a3c.a3c_data.ipynb",
         "A3CLearner": "12_a3c.a3c_data.ipynb",
         "A3CTrainer": "12_a3c.a3c_data.ipynb",
         "AvgEpisodeRewardMetric": "13_metrics.ipynb"}

modules = ["wrappers.py",
           "callbacks.py",
           "basic_agents.py",
           "learner.py",
           "data.py",
           "async_data.py",
           "basic_train.py",
           "a3c/a3c_data.py",
           "metrics.py"]

doc_url = "https://josiahls.github.io/fastrl/"

git_url = "https://github.com/josiahls/fastrl/tree/master/"

def custom_doc_links(name): return None
