# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PixelObservationWrapper": "01_wrappers.ipynb",
         "STATE_KEY": "01_wrappers.ipynb",
         "ActionSelector": "03_basic_agents.ipynb",
         "ArgmaxActionSelector": "03_basic_agents.ipynb",
         "EpsilonGreedyActionSelector": "03_basic_agents.ipynb",
         "ProbabilityActionSelector": "03_basic_agents.ipynb",
         "default_states_preprocessor": "03_basic_agents.ipynb",
         "float32_preprocessor": "03_basic_agents.ipynb",
         "BaseAgent": "03_basic_agents.ipynb",
         "TestAgent": "03_basic_agents.ipynb",
         "DiscreteAgent": "03_basic_agents.ipynb",
         "DQNAgent": "03_basic_agents.ipynb",
         "TargetNet": "03_basic_agents.ipynb",
         "PolicyAgent": "03_basic_agents.ipynb",
         "ActorCriticAgent": "03_basic_agents.ipynb",
         "TotalRewards": "04_metrics.ipynb",
         "RewardMetric": "04_metrics.ipynb",
         "NGamesMetric": "04_metrics.ipynb",
         "EnvLists": "05_data.ipynb",
         "EnvMakeTfm": "05_data.ipynb",
         "DoneStateEnv:d:bool;s:np.array;env": "05_data.ipynb",
         "EnvResetTfm": "05_data.ipynb",
         "DoneStateEnv.__repr__": "05_data.ipynb",
         "EnvGenUnwrapTfm": "05_data.ipynb",
         "env_display": "05_data.ipynb",
         "Experience:d:bool;s:np.ndarray;sp:np.ndarray;r:float;a": "05_data.ipynb",
         "EnvStepTfm": "05_data.ipynb",
         "FloatifyCallback": "06_basic_train.ipynb",
         "FakeRunCallback": "06_basic_train.ipynb",
         "LatentLossBuffer": "06_basic_train.ipynb",
         "AgentLearner": "06_basic_train.ipynb",
         "a3c_data_fitter": "12_a3c.a3c_data.ipynb",
         "A3CLearner": "12_a3c.a3c_data.ipynb",
         "r_estimate": "12_a3c.a3c_data.ipynb",
         "unbatch": "12_a3c.a3c_data.ipynb",
         "A3CTrainer": "12_a3c.a3c_data.ipynb",
         "debug_batch": "12_a3c.a3c_data.ipynb"}

modules = ["wrappers.py",
           "callbacks.py",
           "basic_agents.py",
           "metrics.py",
           "data.py",
           "basic_train.py",
           "a3c/a3c_data.py"]

doc_url = "https://josiahls.github.io/fastrl/"

git_url = "https://github.com/josiahls/fastrl/tree/master/"

def custom_doc_links(name): return None
