# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/06_basic_train.ipynb (unless otherwise specified).

__all__ = ['AgentLearner']

# Cell
from fastai.basic_data import *
from fastai.basic_train import *
from fastai.torch_core import *
from dataclasses import asdict
import logging
import gym

from .basic_agents import *

# Cell
@dataclass
class AgentLearner():
    data:DataBunch
    model:nn.Module
    agent:BaseAgent=BaseAgent()
    training:bool=False

    def predict(self,s):
        return self.agent(s,None)