# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_basic_train.ipynb (unless otherwise specified).

__all__ = ['AgentLearner']

# Cell
from fastai.basic_data import *
from fastai.basic_train import *
from fastai.torch_core import *
from dataclasses import asdict
import logging
import gym

# Cell
@dataclass
class AgentLearner():
    data:DataBunch
    model:nn.Module
    training:bool=False

    def predict(self,s,agent_s=None):
        return self.data.dl(ds_type=DatasetType.Valid if self.training else DatasetType.Train).envs[0].action_space.sample(),agent_s