package:
  name: fastrl2
  version: 2.0.12
source:
  sha256: 09ea1892dfc62dc3d7dfb1265ab575fa081b84b08f7370920d7a7ea9bbaf6799
  url: https://files.pythonhosted.org/packages/a6/9e/69228df928d49daefdd6a4fccf5ea617f146aa317c8a2d5039f030d358ee/fastrl2-2.0.12.tar.gz
about:
  dev_url: https://josiahls.github.io
  doc_url: https://josiahls.github.io
  home: https://josiahls.github.io
  license: Apache Software
  license_family: APACHE
  summary: fastrl is a reinforcement learning library that extends Fastai. This project
    is not affiliated with fastai or Jeremy Howard.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - josiahls
requirements:
  host:
  - pip
  - python
  - packaging
  - fastai>=2.0.0
  run:
  - pip
  - python
  - packaging
  - fastai>=2.0.0
test:
  imports:
  - fastrl2
