name: Python Package using Conda

on:
  push:
    branches:
      - master
  workflow_dispatch: #allows you to trigger manually

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        conda install -c pytorch -c conda-build fastai fastrelease
        fastrelease_conda_package --upload_user josiahls  --build_args '-c pytorch -c fastai'
    - name: Test with pytest
      run: |
        conda install fastrl2
        fastrl
